baseURL = 'http://example.org/'
languageCode = 'en-us'
contentDir = "content/en"
title = 'templ'
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
